https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-your-first-pipeline

In [ ]:
# import azureml.core
from azureml.core import Workspace, Datastore

ws = Workspace.from_config()

In [24]:
from azureml.core.conda_dependencies import CondaDependencies 

#myenv = CondaDependencies.create(conda_packages=['numpy','scikit-learn','cython'], pip_packages=['azureml-sdk[automl]'])
myenv = CondaDependencies()
myenv.add_conda_package("numpy")
myenv.add_conda_package('scikit-learn')
myenv.add_conda_package('pip')

myenv.add_conda_package("cython")
myenv.add_pip_package("azureml-sdk")
myenv.add_pip_package("pandas")
myenv.add_pip_package("keras")
myenv.add_pip_package("tensorflow==2.1.0-rc0")
myenv.add_pip_package("tensorflow-hub")

with open("myenv.yml","w") as f:
    f.write(myenv.serialize_to_string())

In [19]:
import yaml
import io
with open("myenv.yml", 'r') as stream:
    data_loaded = yaml.safe_load(stream)
data_loaded

{'name': 'project_environment',
 'dependencies': ['python=3.6.2',
  {'pip': ['azureml-defaults',
    'azureml-sdk',
    'pandas',
    'keras',
    'tensorflow==2.1.0-rc0',
    'tensorflow-hub']},
  'numpy',
  'scikit-learn',
  'pip',
  'cython'],
 'channels': ['conda-forge']}

### Simple Keras Training at local

In [13]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(set(iris_data.target))

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=100)


Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
{0, 1, 2}
Neural Network Model Summary: 
Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


Epoch 1/100
 - 0s - loss: 1.7438 - accuracy: 0.3750
Epoch 2/100
 - 0s - loss: 1.3702 - accuracy: 0.3750
Epoch 3/100
 - 0s - loss: 1.0702 - accuracy: 0.5500
Epoch 4/100
 - 0s - loss: 0.9333 - accuracy: 0.7083
Epoch 5/100
 - 0s - loss: 0.8563 - accuracy: 0.7083
Epoch 6/100
 - 0s - loss: 0.8004 - accuracy: 0.7083
Epoch 7/100
 - 0s - loss: 0.7573 - accuracy: 0.7083
Epoch 8/100
 - 0s - loss: 0.7182 - accuracy: 0.7083
Epoch 9/100
 - 0s - loss: 0.6833 - accuracy: 0.7083
Epoch 10/100
 - 0s - loss: 0.6514 - accuracy: 0.7083
Epoch 11/100
 - 0s - loss: 0.6190 - accuracy: 0.7083
Epoch 12/100
 - 0s - loss: 0.5864 - accuracy: 0.7167
Epoch 13/100
 - 0s - loss: 0.5577 - accuracy: 0.7167
Epoch 14/100
 - 0s - loss: 0.5321 - accuracy: 0.7333
Epoch 15/100
 - 0s - loss: 0.5103 - accuracy: 0.7333
Epoch 16/100
 - 0s - loss: 0.4945 - accuracy: 0.7750
Epoch 17/100
 - 0s - loss: 0.4699 - accuracy: 0.7333
Epoch 18/100
 - 0s - loss: 0.4378 - accuracy: 0.7500
Epoch 19/100
 - 0s - loss: 0.4181 - accuracy: 0.8333
Ep

array([1, 0, 1, 0, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 0, 1, 1, 1, 0, 0, 2, 1,
       2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 1, 1, 1, 1, 2, 2,
       2, 1, 0, 0, 2, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 1, 2, 0, 1, 1,
       0, 0, 0, 2, 1, 2, 2, 2, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 0,
       0, 2, 0, 2, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 0, 1, 2, 0, 1, 1, 2, 2,
       1, 0, 2, 1, 0, 2, 0, 0, 1, 2])

In [52]:
%%writefile score_keras.py
import json
import numpy as np
import os
from keras.models import model_from_json
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

from azureml.core.model import Model

def init():
    global model
    
    model_root = Model.get_model_path('keras_model')
    print (model_root)
    # load json and create model
    json_file = open(os.path.join(model_root, 'model.json'), 'r')
    model_json = json_file.read()
    json_file.close()
    model = model_from_json(model_json)
    # load weights into new model
    model.load_weights(os.path.join(model_root, "model.h5"))   
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    
def run(raw_data):
    try:
        data = np.array(json.loads(raw_data)['data'])
        # make prediction
        y_hat = np.argmax(model.predict(data), axis=1)
        return y_hat.tolist()
    except Exception as e:
        error = str(e)
        return error

Overwriting score_keras.py


In [4]:
f = open("score_keras.py", "r")
print(f.read())

import json
import numpy as np
import os
from keras.models import model_from_json
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

from azureml.core.model import Model

def init():
    global model
    
    model_root = Model.get_model_path('keras_model')
    print (model_root)
    # load json and create model
    json_file = open(os.path.join(model_root, 'model.json'), 'r')
    model_json = json_file.read()
    json_file.close()
    model = model_from_json(model_json)
    # load weights into new model
    model.load_weights(os.path.join(model_root, "model.h5"))   
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    
def run(raw_data):
    try:
        data = np.array(json.loads(raw_data)['data'])
        # make prediction
        y_hat = np.argmax(model.predict(data), axis=1)
        return y_hat.tolist()
    except Exception as e:
        error = str(e)
        return error



In [100]:
%%writefile train_keras.py
# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license.

from sklearn.datasets import load_diabetes
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from azureml.core.run import Run
from sklearn.externals import joblib
from azureml.core import Dataset, Run
import pandas as pd
import os
import numpy as np
import glob


run = Run.get_context()
workspace = run.experiment.workspace
ws = run.experiment.workspace

####################################
print ("#####################Training######################")

print ("#########Data Preperation#######")
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(set(iris_data.target))

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

print ("#########Data Preperation Completed#######")


print ("#########Model Preperation ######")
# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=100)
print ("#########Model Fit Completed#######")

print ("#####################Training Completed######################")


print ("####################Model Register###############")


model_name='keras_model'


# create a ./outputs/model folder in the compute target
# files saved in the "./outputs" folder are automatically uploaded into run history
os.makedirs('./outputs/model', exist_ok=True)

# serialize NN architecture to JSON
model_json = model.to_json()
# save model JSON
with open('./outputs/model/model.json', 'w') as f:
    f.write(model_json)
# save model weights
model.save_weights('./outputs/model/model.h5')
print("model saved in ./outputs/model folder")

run.upload_file(model_name, "./outputs/model/model.h5")


ws = run.experiment.workspace

try:
    from azureml.core.model import Model
    model=Model(workspace=ws,name=model_name)
    print ("Old Model Version",model.version)
except:
    print ("No old model found")
    
#Important step of registering
print ("Registering using model name",model_name)
model = run.register_model(model_name=model_name, model_path='outputs/model')
print ("Registering Completed",model_name)

from azureml.core.model import Model
model=Model(workspace=ws,name=model_name)
print ("New Model Version",model.version)

print ("#####################Training completed and Model is registered######################")

# #Deployment
print ("###########Deployment Step##################\n")

#It must only consist of lowercase letters, 
#numbers, or dashes, start with a letter, end with a letter or number, and be between 3 and 32 characters long."
aci_service_name = 'kerasservice'


from azureml.core.webservice import AciWebservice
from azureml.core.webservice import Webservice
from azureml.core import Environment
from azureml.core.webservice import Webservice
from azureml.core.model import Model, InferenceConfig


from azureml.core.model import Model
#Always gets latest version
model=Model(workspace=ws,name=model_name)
print (model.version)


try:
    print (Webservice(name=aci_service_name, workspace=ws).scoring_uri)
except:
    pass
print(aci_service_name)

#Try few times to update service and if failed then go for except block.
try:
    for _ in range(2):
        print (_)
        try:
            print ("Updating Service")
            # Retrieve existing service.
            from azureml.core.webservice import Webservice
            service_original = Webservice(name=aci_service_name, workspace=ws)
            inference_config = InferenceConfig(entry_script="score_keras.py"
                                              ,runtime = "python"
                                               ,conda_file="myenv.yml"
                                              )
            # Update to new model(s).
            service_original.update(models=[model], inference_config=inference_config)
            service_original.wait_for_deployment(show_output=True)    
            print(service_original.state)
            break
        except:
            pass
    else:
        print (induced_error_to_go_to_catch_block) # both tries failed
    
except:
    from azureml.core.image import Image, ContainerImage
    from azureml.core.webservice import Webservice
    try:
        service_original = Webservice(name=aci_service_name, workspace=ws)
    except:
        pass
    from azureml.core.model import Model
    try:
        if (service_original.state!='Healthy'):
            from azureml.core.webservice import Webservice
            service_original = Webservice(name='kerasservice', workspace=ws)
            print (service_original.state)
            print ("Deleting as state is not healthy")
            service_original.delete()
    except:
        pass
    aci_service_name="kerasservice"
    try:
        print ("Get Image")
        image=Image(ws, name='kerasimage')
    except:
        print ("Creating Image as not found")
        image_config = ContainerImage.image_configuration(runtime= "python",
                                         execution_script="score_keras.py",
                                         conda_file="myenv.yml"
                                                         )
        image = Image.create(name = "kerasimage",models = [model],image_config = image_config, workspace = ws)
        image.wait_for_creation(show_output = True)
    aciconfig = AciWebservice.deploy_configuration(cpu_cores = 2, memory_gb = 2)
    service_original = Webservice.deploy_from_image(deployment_config = aciconfig,
                                                    image = image,
                                                    name = aci_service_name,
                                                    workspace = ws)
    service_original.wait_for_deployment(show_output=True)
    print(service_original.state)
    print(service_original.scoring_uri)

Overwriting train_keras.py


### Runtime Compute Target

In [ ]:
%%time
import azureml.core
import os
from azureml.core import Workspace, Datastore, Experiment
from azureml.data.data_reference import DataReference
from azureml.core.dataset import Dataset

from azureml.core.compute import ComputeTarget, AmlCompute

ws = Workspace.from_config() 

# First, list the supported VM families for Azure Machine Learning Compute
# print(AmlCompute.supported_vmsizes(workspace=ws))

###################Runtime
from azureml.core.runconfig import RunConfiguration
# Create a new runconfig object
run_config = RunConfiguration()

# Signal that you want to use AmlCompute to execute the script
run_config.target = "amlcompute"

# AmlCompute is created in the same region as your workspace
# Set the VM size for AmlCompute from the list of supported_vmsizes
run_config.amlcompute.vm_size = 'STANDARD_D2_V2'
####################


experiment = Experiment(ws, 'MyExperiment') 

# # Use a RunConfiguration to specify some additional requirements for this step.
from azureml.core.runconfig import RunConfiguration
from azureml.core.conda_dependencies import CondaDependencies
from azureml.core.runconfig import DEFAULT_CPU_IMAGE
############################################################
# # create a new runconfig object
# run_config = RunConfiguration()

# #Point to created compute target
# compute_target = ws.compute_targets["hari-compu-mlc"]
# #Point to created Experiment

# ##################################

# # enable Docker 
# run_config.environment.docker.enabled = True

# # set Docker base image to the default CPU-based image
# run_config.environment.docker.base_image = DEFAULT_CPU_IMAGE

# # use conda_dependencies.yml to create a conda environment in the Docker image for execution
# run_config.environment.python.user_managed_dependencies = False
#############################################################################

# specify CondaDependencies obj
run_config.environment.python.conda_dependencies = CondaDependencies.create(pip_packages=['azureml-sdk',
                                                                             'azureml-dataprep[pandas,fuse]',
                                                                             'scikit-learn','keras','tensorflow==2.1.0-rc0','tensorflow-hub',
                                                                                         'wget','xlrd'])


from azureml.pipeline.steps import PythonScriptStep

project_folder=os.getcwd()

trainStep = PythonScriptStep(
    script_name="train_keras.py",
    compute_target=('amlcompute', 'AmlCompute'),
    source_directory=project_folder,
    runconfig=run_config,
    allow_reuse=False
)

from azureml.pipeline.core import Pipeline

pipeline = Pipeline(workspace=ws, steps=trainStep)

pipeline_run = experiment.submit(pipeline,regenerate_outputs=True)
pipeline_run.wait_for_completion(show_output=True)

### Uncomment and run this in case deployment fails through pipeline because of timeout

In [ ]:
# print ("###########Deployment Step##################\n")

# # import azureml.core
# from azureml.core import Workspace, Datastore

# ws = Workspace.from_config()

# #It must only consist of lowercase letters, 
# #numbers, or dashes, start with a letter, end with a letter or number, and be between 3 and 32 characters long."
# aci_service_name = 'kerasservice'


# from azureml.core.webservice import AciWebservice
# from azureml.core.webservice import Webservice
# from azureml.core import Environment
# from azureml.core.webservice import Webservice
# from azureml.core.model import Model, InferenceConfig


# from azureml.core.model import Model
# #Always gets latest version
# model_name='keras_model'
# model=Model(workspace=ws,name=model_name)
# print (model.version)


# try:
#     print (Webservice(name=aci_service_name, workspace=ws).scoring_uri)
# except:
#     pass
# print(aci_service_name)
# try:
#     print ("Updating Service")
#     # Retrieve existing service.
#     from azureml.core.webservice import Webservice
#     service_original = Webservice(name=aci_service_name, workspace=ws)
#     inference_config = InferenceConfig(entry_script="score_keras.py"
#                                       ,runtime = "python"
#                                        ,conda_file="myenv.yml"
#                                       )
#     # Update to new model(s).
#     service_original.update(models=[model], inference_config=inference_config)
#     service_original.wait_for_deployment(show_output=True)    
#     print(service_original.state)
# except:
#     from azureml.core.image import Image, ContainerImage
#     from azureml.core.webservice import Webservice
#     try:
#         service_original = Webservice(name=aci_service_name, workspace=ws)
#     except:
#         pass
#     from azureml.core.model import Model
#     try:
#         if (service_original.state!='Healthy'):
#             from azureml.core.webservice import Webservice
#             service_original = Webservice(name='kerasservice', workspace=ws)
#             print (service_original.state)
#             print ("Deleting as state is not healthy")
#             service_original.delete()
#     except:
#         pass
#     aci_service_name="kerasservice"
#     try:
#         print ("Get Image")
#         image=Image(ws, name='kerasimage')
#     except:
#         print ("Creating Image as not found")
#         image_config = ContainerImage.image_configuration(runtime= "python",
#                                          execution_script="score_keras.py",
#                                          conda_file="myenv.yml"
#                                                          )
#         image = Image.create(name = "kerasimage",models = [model],image_config = image_config, workspace = ws)
#         image.wait_for_creation(show_output = True)
#     aciconfig = AciWebservice.deploy_configuration(cpu_cores = 2, memory_gb = 2)
#     service_original = Webservice.deploy_from_image(deployment_config = aciconfig,
#                                                     image = image,
#                                                     name = aci_service_name,
#                                                     workspace = ws)
#     service_original.wait_for_deployment(show_output=True)
#     print(service_original.state)
#     print(service_original.scoring_uri)

### Test Web Service

In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(set(iris_data.target))

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

Using TensorFlow backend.


Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
{0, 1, 2}


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [8]:
test_x

array([[6.3, 2.7, 4.9, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [6.4, 2.7, 5.3, 1.9],
       [6.4, 3.1, 5.5, 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 3.4, 5.6, 2.4],
       [6.5, 3. , 5.8, 2.2],
       [6. , 3.4, 4.5, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [6.8, 2.8, 4.8, 1.4],
       [5.1, 3.4, 1.5, 0.2],
       [6.1, 3. , 4.6, 1.4],
       [5.5, 2.6, 4.4, 1.2],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [6.2, 3.4, 5.4, 2.3],
       [6.1, 3. , 4.9, 1.8],
       [5.1, 3.5, 1.4, 0.3],
       [4.9, 3.6, 1.4, 0.1],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [6.3, 2.3, 4.4, 1.3],
       [6.4, 3.2, 4.5, 1.5],
       [6.7, 3.1, 5.6, 2.4],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 3. , 4.2, 1.2],
       [5.2, 2.7, 3.9, 1.4]])

In [ ]:
# import azureml.core
from azureml.core import Workspace, Datastore
ws = Workspace.from_config()
from azureml.core.webservice import Webservice
service_original = Webservice(name='kerasservice', workspace=ws)

In [102]:
import json
import numpy as np
import pandas as pd
test_samples = json.dumps({"data": test_x.tolist()})
pred_actual=pd.DataFrame(service_original.run(input_data=test_samples),np.argmax(test_y,axis=1)).reset_index()
pred_actual.columns=['Prediction','Actual']
pred_actual

Prediction  Actual
0            2       2
1            2       2
2            2       2
3            2       2
4            0       0
5            2       2
6            2       2
7            2       2
8            2       2
9            1       1
10           1       2
11           1       1
12           0       0
13           1       1
14           1       1
15           1       1
16           1       1
17           2       2
18           2       2
19           0       0
20           0       0
21           1       1
22           0       0
23           0       0
24           1       1
25           1       1
26           2       2
27           2       2
28           1       1
29           1       1

## Appendix:  Publish and Schedule Pipeline

In [ ]:
pipeline_name = "KerasPipeline"
print(pipeline_name)

published_pipeline = pipeline.publish(
    name=pipeline_name, 
    description=pipeline_name)
print("Newly published pipeline id: {}".format(published_pipeline.id))

##### Schedule

In [ ]:
#https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/machine-learning-pipelines/intro-to-pipelines/aml-pipelines-setup-schedule-for-a-published-pipeline.ipynb
from azureml.pipeline.core.schedule import ScheduleRecurrence, Schedule
# #"Minute", "Hour", "Day", "Week", or "Month"
recurrence = ScheduleRecurrence(frequency="Minute", interval=15)

schedule = Schedule.create(workspace=ws, name="KerasPipelineSchedule",
                           pipeline_id=published_pipeline.id, 
                           experiment_name='MyExperiment',
                           recurrence=recurrence,
                           wait_for_provisioning=True)

# You may want to make sure that the schedule is provisioned properly
# before making any further changes to the schedule

print("Created schedule with id: {}".format(schedule.id))

##### Update Schedule

In [ ]:
recurrence = ScheduleRecurrence(frequency="Minute", interval=60) # Runs every two hours

fetched_schedule = Schedule.get(ws, schedule.id)

fetched_schedule.update(name="My_Updated_Schedule", 
                        description="Updated_Schedule_Run", 
                        status='Active', 
                        wait_for_provisioning=True,
                        recurrence=recurrence)

fetched_schedule = Schedule.get(ws, fetched_schedule.id)

print("Updated schedule:", fetched_schedule.id, 
      "\nNew name:", fetched_schedule.name,
      "\nNew frequency:", fetched_schedule.recurrence.frequency,
      "\nNew status:", fetched_schedule.status)

####  Delete all piplelines and schedules: Optional. 

In [6]:
# print ("Run this one to delete all the schedules and pipelines in workspace by setting delete_all_pipeline_schedule=True")
# delete_all_pipeline_schedule=True
# from azureml.pipeline.core.schedule import ScheduleRecurrence, Schedule
# from azureml.pipeline.core import PublishedPipeline
# if delete_all_pipeline_schedule:

#     for published_pipeline in PublishedPipeline.list(ws):
#         published_pipeline_id=published_pipeline.id
#         print (published_pipeline_id)
#         try:
#             schedules = Schedule.list(ws, pipeline_id=published_pipeline_id)
#             for schedule in schedules: 
#                 print("Schedule ID",schedule.id)
#                 schedule.disable(wait_for_provisioning=True)
#                 print ("Updated Status of Schedule",schedule.status)
#         except:
#             print ("Schedule not found")
#         delete_pipeline=True
#         if delete_pipeline:
#             p = PublishedPipeline.get(ws, id=published_pipeline_id)
#             p.disable()